### PR TITLE
Changed cookiebot cookie type to necessary

### PR DESCRIPTION
**Pull request by afrancht**
Two changes:
* Cookiebot cookies should be in the strictly necessary section as they enable the user to consent to other cookie types. If these are not strictly necessary, then it is not possible to set consent for the rest.
* Added .gitignore file so that people don't push .DS_Store files by mistake.

### CODE REVIEW

**Comment by Paapst** [comment]
Hi, I would suggest to @jkwakman to not merge the proposed change because the Cookiebot cookies are actually already in the correct section. The purpose is Functional. Cookies that are categorized under “Functional” are always allowed (not only in the EU, but also under other international cookie and Privacaylaws in the UK, the US, Brasil, Canada etc) and do not need consent.
Please also see: https://cookiedatabase.org/function-and-purpose-of-cookies/
As you can see there the purpose “Functional” is also known as strictly necessary, technical or essential. These are cookies that are necessary for a website to function properly. There is no legal nor practical need to break Functional out into those separate categories because for all the cookies that are categorized under Functional, it is not necessary to ask for consent.

**Comment by jkwakman** [comment]
Dear Alex,

Thank you for you're valueable input. I have added the DS_Store in the git ignore. 

I agree with the feedback of Mathieu Paapst (thank you for you're expertise and experience). We currently have the categories Functional, Marketing and Analytics. Functional are always allowed and we do not differentiate between Functional and Necessary. There is no legal or practical need to split this category into Functional and Necessary

Kind regards,

Jack Kwakman

**Comment by afrancht** [comment]
Hi @jkwakman and @Paapst,

Thank you for the clarification. I was not aware of the categorisation system that you had used. I thought that Functional was short for `functionality` cookies and since, there are only three categories present in the current state of the DB, I got confused.

Note that in the UK we are accustomed to see strictly necessary (example can be found [here](https://uk.practicallaw.thomsonreuters.com/w-019-8333?transitionType=Default&contextData=(sc.Default)) and I suggest implementing a readme file so that other people are not confused. I have created another PR.

https://github.com/jkwakman/Open-Cookie-Database/pull/13

**Comment by Paapst** [comment]
Hi @afrancht and @jkwakman 
I know that some CMP's are indeed using other terms such as strictly neccesary. I also know that ICO used the term wheer other DPA's used the term Functional instead. Nowadays, also in the UK there are many examples where only "Functional" is being used (example can be found [here](https://beale-law.com/cookie-policy-uk/) with this UK Law firm,  but also here on this [NHS](https://www.blood.co.uk/cookies/) website. 

I think it is a good idea to use a readme in order to explain the categorisation system.

**Pull request closed without merging**
