### PR TITLE
feat: consider replacing `None` to an empty field

### PR DESCRIPTION
**Pull request by pareyesv**
Consider discussing the following changes:

- Change Platform name: `Advertiser's website domain` -> (empty field)
- Change `None` -> (empty field)

### CODE REVIEW

**Comment by MattHag** [comment]
In addition to that, `N/A` should also get -> (empty field)

**Comment by jkwakman** [comment]
This is a tough decision to make. Many people will already apply this text in their software. I will have to think about this suggestion and how we should handle this in the near future.

**Comment by hwgn** [comment]
I would vouch in favor of these decisions - right now, I translate the string `Advertiser's website domain` to an empty string anyway, I would assume most implementations do this, and generally, having an empty field would be the more concrete indicator of "any" or "none" - e.g., if someone wrote `Advertisers website domain` one would need a Regex to catch these typos/alternative versions.

In the long run, this repo could make use of versioning and announce breaking changes like this to users to ensure their project won't fail with the new syntax.

**Comment by jkwakman** [comment]
Dear MattHag, hwgn and pareyesv,

Thank you for the valuable feedback. I really appreciate the input. After careful consideration I have made the changes in the database.  

Latest version removes the following identifiers from the file:

N/A
None
Advertiser's website domain
Website domain

V0.1 still has the old setup but is deprecated from now on. 

If you have any more questions or feedback please let me know. 

Kind regards,

Jack Kwakman

**Pull request closed without merging**
