### PR TITLE
Add Intercom cookies

### PR DESCRIPTION
**Pull request by andywaite**
How are the IDs generated?

### CODE REVIEW

**Comment by jkwakman** [comment]
Dear Andrew,

We use UUID's as an ID. You can generate them with libraries or even online:
https://www.uuidgenerator.net/version4

Can you please add UUID's to the commit? 

Kind regards,

Jack Kwakman

**Review by jkwakman — APPROVED** [review]
Cookies are found in docs:
https://www.intercom.com/help/en/articles/2361922-intercom-messenger-cookies

**Comment by jkwakman** [comment]
Dear Andy,

Thank you for the additions. There was an unexpected large dif on the CSV file. I have added the additions to master an will close this ticket for now. All you're changes are accepted and added to master. 

Thank you!

Kind regards,

Jack Kwakman

**Comment by andywaite** [comment]
Apologies @jkwakman - for this first one I opened it in OpenOffice and saved it out. I think it decided to quote some strings that previously weren't quoted (or vice-versa).

For subsequent changes I've just added the new lines using a text editor so shouldn't have the same issues

**Pull request closed without merging**
